# Setup
title:               'Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                 'https://thaong91.github.io/'
baseurl:             'tn-appdev-spr22/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Thao Nguyen
  url:               https://twitter.com/
  email:             thao@chicagobooth.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
